class AlgerianAddresses {
  static const Map<String, List<String>> wilayas = {
    'Adrar': [
      'Adrar',
      'Timimoun',
      'Aoulef',
      'Reggane',
      'In Salah',
      'Aougrout',
      'Tit',
      'Zaouiet Kounta',
      'Tamentit',
      'Fenoughil',
      'Bouda',
      'Sali',
      'Akabli',
      'Metarfa',
      'Ouled Ahmed Timmi',
      'Boudghène',
      'Talmine',
      'Ouled Saïd',
      'Zaouiet Lahdar',
      'Aghlal',
      'N\'Goussa',
      'Sbaa',
      'Tinerkouk',
      'Deldoul',
      'Sali',
      'Tamest',
      'Fenoughil',
      'Talmine',
      'Ouled Saïd',
      'Zaouiet Lahdar',
    ],
    'Chlef': [
      'Chlef',
      'Oued Fodda',
      'Boukadir',
      'Beni Rached',
      'Talassa',
      'Harenfa',
      'Ouled Fares',
      'Sidi Akkacha',
      'El Marsa',
      'Ténès',
      'Beni Haoua',
      'Sobha',
      'Harchoun',
      'Ouled Ben Abdelkader',
      'Lazaria',
      'Oued Goussine',
      'Dahra',
      'Sidi M\'Hamed Ben Ali',
      'Abou El Hassan',
      'El Karimia',
      'Taougrit',
      'Hadjadj',
      'Larbaa',
      'Beni Bouateb',
      'Oued Sly',
      'Breira',
      'Beni Rached',
      'Chettia',
      'Moussadek',
      'Harenfa',
      'Ouled Fares',
      'Sidi Akkacha',
      'El Marsa',
      'Ténès',
      'Beni Haoua',
      'Sobha',
      'Harchoun',
      'Ouled Ben Abdelkader',
      'Lazaria',
      'Oued Goussine',
      'Dahra',
      'Sidi M\'Hamed Ben Ali',
      'Abou El Hassan',
      'El Karimia',
      'Taougrit',
      'Hadjadj',
      'Larbaa',
      'Beni Bouateb',
      'Oued Sly',
      'Breira',
    ],
    'Laghouat': [
      'Laghouat',
      'Ksar El Hirane',
      'Bennacer Benchohra',
      'Sidi Makhlouf',
      'El Haouaita',
      'Tadjmout',
      'Kheneg',
      'Aflou',
      'El Assafia',
      'Oued Morra',
      'Tadjrouna',
      'Hassi R\'Mel',
      'Ain Mahdi',
      'Touggourt',
      'Sidi Bouzid',
      'El Ghicha',
      'Hassi Delaa',
      'Mekhareg',
      'M\'Guiden',
      'Sebgag',
      'Taouiala',
      'El Kheneg',
      'Brida',
      'Ain Sidi Ali',
      'Oued Morra',
      'Tadjrouna',
      'Hassi R\'Mel',
      'Ain Mahdi',
      'Touggourt',
      'Sidi Bouzid',
      'El Ghicha',
      'Hassi Delaa',
      'Mekhareg',
      'M\'Guiden',
      'Sebgag',
      'Taouiala',
      'El Kheneg',
      'Brida',
      'Ain Sidi Ali',
    ],
    'Oum El Bouaghi': [
      'Oum El Bouaghi',
      'Aïn Beïda',
      'Ksar Sbahi',
      'Ouled Gacem',
      'El Belala',
      'Aïn Babouche',
      'Berriche',
      'Ouled Zouaï',
      'El Amiria',
      'Sigus',
      'F\'Kirina',
      'Ouled Hamla',
      'Aïn M\'Lila',
      'El Harmilia',
      'Ouled Maâche',
      'El Djazia',
      'Aïn Zitoun',
      'Meskiana',
      'Aïn Fakroun',
      'El Aouinet',
      'Rahia',
      'Ouled Zouaï',
      'El Amiria',
      'Sigus',
      'F\'Kirina',
      'Ouled Hamla',
      'Aïn M\'Lila',
      'El Harmilia',
      'Ouled Maâche',
      'El Djazia',
      'Aïn Zitoun',
      'Meskiana',
      'Aïn Fakroun',
      'El Aouinet',
      'Rahia',
    ],
    'Batna': [
      'Batna',
      'Merouana',
      'Seriana',
      'Menaa',
      'El Madher',
      'Tazoult',
      'N\'Gaous',
      'Guigba',
      'Inoughissen',
      'Ouyoun El Assafir',
      'Djerma',
      'Ichmoul',
      'Fesdis',
      'Aïn Touta',
      'Ouled Si Slimane',
      'Bouzina',
      'Chemora',
      'Djezzar',
      'T\'Kout',
      'El Mizaraa',
      'Aïn Djasser',
      'Ouled Ammar',
      'Lazrou',
      'Boumia',
      'Ouled Aouf',
      'Timgad',
      'Ras El Aioun',
      'Foum Toub',
      'Beni Foudhala El Hakania',
      'Oued El Ma',
      'Talkhamt',
      'Aïn Yagout',
      'Ghassira',
      'Boumagueur',
      'Barika',
      'Djezzar',
      'T\'Kout',
      'El Mizaraa',
      'Aïn Djasser',
      'Ouled Ammar',
      'Lazrou',
      'Boumia',
      'Ouled Aouf',
      'Timgad',
      'Ras El Aioun',
      'Foum Toub',
      'Beni Foudhala El Hakania',
      'Oued El Ma',
      'Talkhamt',
      'Aïn Yagout',
      'Ghassira',
      'Boumagueur',
      'Barika',
    ],
    'Béjaïa': [
      'Béjaïa',
      'Amizour',
      'Feraoun',
      'Taourirt Ighil',
      'Chellata',
      'Darguina',
      'Toudja',
      'Aït R\'Zine',
      'Aokas',
      'Barbacha',
      'Kendira',
      'Tifra',
      'Ighil Ali',
      'Aghbalou',
      'Aït Smail',
      'Souk El Tenine',
      'Mechtras',
      'Sidi Aïch',
      'El Kseur',
      'Tichy',
      'Aït Oumalou',
      'Ighram',
      'Amalou',
      'Ighil Oumced',
      'Tala Yfassene',
      'Bouhamza',
      'Beni Djellil',
      'Adekar',
      'Akfadou',
      'Seddouk',
      'Tazmalt',
      'Aït R\'Zine',
      'Aokas',
      'Barbacha',
      'Kendira',
      'Tifra',
      'Ighil Ali',
      'Aghbalou',
      'Aït Smail',
      'Souk El Tenine',
      'Mechtras',
      'Sidi Aïch',
      'El Kseur',
      'Tichy',
      'Aït Oumalou',
      'Ighram',
      'Amalou',
      'Ighil Oumced',
      'Tala Yfassene',
      'Bouhamza',
      'Beni Djellil',
      'Adekar',
      'Akfadou',
      'Seddouk',
      'Tazmalt',
    ],
    'Biskra': [
      'Biskra',
      'Oumache',
      'Branis',
      'Chetma',
      'Ouled Djellal',
      'Ras El Oued',
      'Bousâada',
      'M\'Sila',
      'Magra',
      'Ouled Derradj',
      'Tolga',
      'Lioua',
      'Doucen',
      'Zeribet El Oued',
      'El Feidh',
      'El Kantara',
      'Aïn Naga',
      'Ouled Sassi',
      'Sidi Okba',
      'Mechouneche',
      'Foughala',
      'Béni Abbès',
      'Igli',
      'Tolga',
      'Lioua',
      'Doucen',
      'Zeribet El Oued',
      'El Feidh',
      'El Kantara',
      'Aïn Naga',
      'Ouled Sassi',
      'Sidi Okba',
      'Mechouneche',
      'Foughala',
      'Béni Abbès',
      'Igli',
    ],
    'Béchar': [
      'Béchar',
      'Ouled Khoudir',
      'Meridja',
      'Kenadsa',
      'Igli',
      'Tabalbala',
      'Béni Abbès',
      'Kerzaz',
      'Timoudi',
      'Ouled Khoudir',
      'Meridja',
      'Kenadsa',
      'Igli',
      'Tabalbala',
      'Béni Abbès',
      'Kerzaz',
      'Timoudi',
    ],
    'Blida': [
      'Blida',
      'Chebli',
      'Bouinan',
      'Oued Alleug',
      'Ouled Yaich',
      'Chiffa',
      'Mouzaia',
      'Souhane',
      'Cheraga',
      'Oued Djer',
      'Beni Mered',
      'Boufarik',
      'El Affroun',
      'Chréa',
      'Ouled Slama',
      'Beni Tamou',
      'Bouarfa',
      'Ben Chabane',
      'Larbaa',
      'Meftah',
      'Souma',
      'Bougara',
      'Guerrouaou',
      'Aïn Romana',
      'Beni Mered',
      'Boufarik',
      'El Affroun',
      'Chréa',
      'Ouled Slama',
      'Beni Tamou',
      'Bouarfa',
      'Ben Chabane',
      'Larbaa',
      'Meftah',
      'Souma',
      'Bougara',
      'Guerrouaou',
      'Aïn Romana',
    ],
    'Bouira': [
      'Bouira',
      'El Asnam',
      'Chorfa',
      'Hadjout',
      'Souk El Had',
      'Bechloul',
      'Bir Ghbalou',
      'Mchedallah',
      'Sour El Ghozlane',
      'Aïn Bessem',
      'Bordj Okhriss',
      'M\'Chedallah',
      'El Hachimia',
      'Aïn Laloui',
      'Haizer',
      'Lakhdaria',
      'Maâla',
      'Oued El Berdi',
      'Ridane',
      'Saharidj',
      'Taghzout',
      'Zbarbar',
      'Aïn El Turc',
      'El Asnam',
      'Chorfa',
      'Hadjout',
      'Souk El Had',
      'Bechloul',
      'Bir Ghbalou',
      'Mchedallah',
      'Sour El Ghozlane',
      'Aïn Bessem',
      'Bordj Okhriss',
      'M\'Chedallah',
      'El Hachimia',
      'Aïn Laloui',
      'Haizer',
      'Lakhdaria',
      'Maâla',
      'Oued El Berdi',
      'Ridane',
      'Saharidj',
      'Taghzout',
      'Zbarbar',
      'Aïn El Turc',
    ],
    'Tamanrasset': [
      'Tamanrasset',
      'Abalessa',
      'In Ghar',
      'In Guezzam',
      'Tazrouk',
      'Idlès',
      'Tit',
      'In Amguel',
      'Foggaret Ezzaouia',
      'Djanet',
      'Illizi',
      'Debdeb',
      'Bordj Omar Driss',
      'In Amenas',
      'Zarzaïtine',
      'Abalessa',
      'In Ghar',
      'In Guezzam',
      'Tazrouk',
      'Idlès',
      'Tit',
      'In Amguel',
      'Foggaret Ezzaouia',
      'Djanet',
      'Illizi',
      'Debdeb',
      'Bordj Omar Driss',
      'In Amenas',
      'Zarzaïtine',
    ],
    'Tébessa': [
      'Tébessa',
      'Bir El Ater',
      'Cheria',
      'Stah Guentis',
      'El Aouinet',
      'Negrine',
      'Bir Dheb',
      'El Ogla',
      'Morsott',
      'El Hamma',
      'Boulhaf Dyr',
      'Bekkaria',
      'Boukhadra',
      'El Ma Labiodh',
      'Safsaf El Ouesra',
      'Ferkane',
      'Negrine',
      'Bir Dheb',
      'El Ogla',
      'Morsott',
      'El Hamma',
      'Boulhaf Dyr',
      'Bekkaria',
      'Boukhadra',
      'El Ma Labiodh',
      'Safsaf El Ouesra',
      'Ferkane',
    ],
    'Tlemcen': [
      'Tlemcen',
      'Bab El Assa',
      'Remchi',
      'El Fehoul',
      'Sabra',
      'Ghazaouet',
      'Marsa Ben M\'Hidi',
      'Aïn Fezza',
      'Ouled Mimoun',
      'Beni Snous',
      'Sidi Djillali',
      'Bensekrane',
      'Chetouane',
      'Mansourah',
      'Nedroma',
      'Souani',
      'Hennaya',
      'Maghnia',
      'Hammam Boughrara',
      'Sidi Medjahed',
      'Beni Ouarsous',
      'Sebdou',
      'El Gor',
      'Ouled Riyah',
      'Aïn Tellout',
      'Beni Snous',
      'Sidi Djillali',
      'Bensekrane',
      'Chetouane',
      'Mansourah',
      'Nedroma',
      'Souani',
      'Hennaya',
      'Maghnia',
      'Hammam Boughrara',
      'Sidi Medjahed',
      'Beni Ouarsous',
      'Sebdou',
      'El Gor',
      'Ouled Riyah',
      'Aïn Tellout',
    ],
    'Tiaret': [
      'Tiaret',
      'Medrissa',
      'Mahdia',
      'Hamadia',
      'Ksar Chellala',
      'Rechaiga',
      'Naima',
      'Mechraâ Sfa',
      'Bougara',
      'Frenda',
      'Aïn Deheb',
      'Takhemaret',
      'Sidi Ali Mellal',
      'Dar Chioukh',
      'Sbaa',
      'Tousnina',
      'Aïn Kermes',
      'Dahmouni',
      'Rahouia',
      'Guertoufa',
      'Sidi Hosni',
      'Medrissa',
      'Mahdia',
      'Hamadia',
      'Ksar Chellala',
      'Rechaiga',
      'Naima',
      'Mechraâ Sfa',
      'Bougara',
      'Frenda',
      'Aïn Deheb',
      'Takhemaret',
      'Sidi Ali Mellal',
      'Dar Chioukh',
      'Sbaa',
      'Tousnina',
      'Aïn Kermes',
      'Dahmouni',
      'Rahouia',
      'Guertoufa',
      'Sidi Hosni',
    ],
    'Tizi Ouzou': [
      'Tizi Ouzou',
      'Aïn El Hammam',
      'Akbil',
      'Azeffoun',
      'Beni Douala',
      'Beni Yenni',
      'Boudjima',
      'Bouzegza Keddara',
      'Draâ Ben Khedda',
      'Draâ El Mizan',
      'Iferhounène',
      'Larbaâ Nath Irathen',
      'Mâatkas',
      'Makouda',
      'Mekla',
      'Mizrana',
      'Ouacif',
      'Ouadhia',
      'Ouaguenoun',
      'Aït Boumahdi',
      'Aït Chafâa',
      'Akerrou',
      'Assi Youcef',
      'Azazga',
      'Azeffoun',
      'Beni Douala',
      'Beni Yenni',
      'Boudjima',
      'Bouzegza Keddara',
      'Draâ Ben Khedda',
      'Draâ El Mizan',
      'Iferhounène',
      'Larbaâ Nath Irathen',
      'Mâatkas',
      'Makouda',
      'Mekla',
      'Mizrana',
      'Ouacif',
      'Ouadhia',
      'Ouaguenoun',
      'Aït Boumahdi',
      'Aït Chafâa',
      'Akerrou',
      'Assi Youcef',
      'Azazga',
    ],
    'Alger': [
      'Alger',
      'Sidi M\'Hamed',
      'Casbah',
      'Bab El Oued',
      'Bologhine',
      'Raïs Hamidou',
      'Hussein Dey',
      'Kouba',
      'Mohammadia',
      'Bordj El Kiffan',
      'El Harrach',
      'Baraki',
      'Oued Smar',
      'Dar El Beïda',
      'Bab Ezzouar',
      'Bordj El Bahri',
      'Bourouba',
      'El Biar',
      'Bouzareah',
      'Birkhadem',
      'Draria',
      'Djasr Kasentina',
      'Hydra',
      'Mohamed Belouizdad',
      'Rouïba',
      'Ouled Fayet',
      'Staoueli',
      'Zéralda',
      'Mahelma',
      'Rahmania',
      'Souidania',
      'Cheraga',
      'Dely Ibrahim',
      'El Achour',
      'Baba Hassen',
      'Douéra',
      'Birtouta',
      'Ouled Chebel',
      'Tessala El Merdja',
      'Les Eucalyptus',
      'Sidi M\'Hamed',
      'Casbah',
      'Bab El Oued',
      'Bologhine',
      'Raïs Hamidou',
      'Hussein Dey',
      'Kouba',
      'Mohammadia',
      'Bordj El Kiffan',
      'El Harrach',
      'Baraki',
      'Oued Smar',
      'Dar El Beïda',
      'Bab Ezzouar',
      'Bordj El Bahri',
      'Bourouba',
      'El Biar',
      'Bouzareah',
      'Birkhadem',
      'Draria',
      'Djasr Kasentina',
      'Hydra',
      'Mohamed Belouizdad',
      'Rouïba',
      'Ouled Fayet',
      'Staoueli',
      'Zéralda',
      'Mahelma',
      'Rahmania',
      'Souidania',
      'Cheraga',
      'Dely Ibrahim',
      'El Achour',
      'Baba Hassen',
      'Douéra',
      'Birtouta',
      'Ouled Chebel',
      'Tessala El Merdja',
      'Les Eucalyptus',
    ],
    'Djelfa': [
      'Djelfa',
      'Aïn Maabed',
      'Aïn Oussara',
      'Benhar',
      'Birine',
      'Bouira Lahdab',
      'Charef',
      'Dar Chioukh',
      'El Guedid',
      'El Idrissia',
      'Faidh El Botma',
      'Guettara',
      'Hassi Bahbah',
      'Hassi El Euch',
      'M\'Liliha',
      'Messaad',
      'Moudjbara',
      'Oum Laadham',
      'Sed Rahal',
      'Sidi Baïzed',
      'Zaafrane',
      'Aïn Maabed',
      'Aïn Oussara',
      'Benhar',
      'Birine',
      'Bouira Lahdab',
      'Charef',
      'Dar Chioukh',
      'El Guedid',
      'El Idrissia',
      'Faidh El Botma',
      'Guettara',
      'Hassi Bahbah',
      'Hassi El Euch',
      'M\'Liliha',
      'Messaad',
      'Moudjbara',
      'Oum Laadham',
      'Sed Rahal',
      'Sidi Baïzed',
      'Zaafrane',
    ],
    'Jijel': [
      'Jijel',
      'El Aouana',
      'Ziama Mansouriah',
      'Taher',
      'Emir Abdelkader',
      'Chekfa',
      'Chahna',
      'El Ancer',
      'El Milia',
      'Sidi Abdelaziz',
      'Taher',
      'Emir Abdelkader',
      'Chekfa',
      'Chahna',
      'El Ancer',
      'El Milia',
      'Sidi Abdelaziz',
    ],
    'Sétif': [
      'Sétif',
      'Aïn Arnat',
      'Aïn Azel',
      'Aïn El Kebira',
      'Aïn Oulmene',
      'Amoucha',
      'Babor',
      'Bazer Sakhra',
      'Belaa',
      'Beni Aziz',
      'Beni Chebana',
      'Beni Fouda',
      'Beni Ouartilane',
      'Bir El Arch',
      'Bouandas',
      'Bougaâ',
      'Bousselam',
      'Boutaleb',
      'Dehamcha',
      'Djemila',
      'Draâ Kebila',
      'El Eulma',
      'El Ouricia',
      'El Ouldja',
      'Guelta Zerka',
      'Hammam Guergour',
      'Hammam Souhna',
      'Maoklane',
      'Mezloug',
      'Oued El Barad',
      'Ouled Addouane',
      'Ouled Sabor',
      'Ouled Si Ahmed',
      'Ouled Tebben',
      'Oum El Adhaim',
      'Ras El Oued',
      'Salah Bey',
      'Serdj El Ghoul',
      'Tachouda',
      'Talaifacene',
      'Taya',
      'Tella',
      'Tizi N\'Bechar',
      'Aïn Arnat',
      'Aïn Azel',
      'Aïn El Kebira',
      'Aïn Oulmene',
      'Amoucha',
      'Babor',
      'Bazer Sakhra',
      'Belaa',
      'Beni Aziz',
      'Beni Chebana',
      'Beni Fouda',
      'Beni Ouartilane',
      'Bir El Arch',
      'Bouandas',
      'Bougaâ',
      'Bousselam',
      'Boutaleb',
      'Dehamcha',
      'Djemila',
      'Draâ Kebila',
      'El Eulma',
      'El Ouricia',
      'El Ouldja',
      'Guelta Zerka',
      'Hammam Guergour',
      'Hammam Souhna',
      'Maoklane',
      'Mezloug',
      'Oued El Barad',
      'Ouled Addouane',
      'Ouled Sabor',
      'Ouled Si Ahmed',
      'Ouled Tebben',
      'Oum El Adhaim',
      'Ras El Oued',
      'Salah Bey',
      'Serdj El Ghoul',
      'Tachouda',
      'Talaifacene',
      'Taya',
      'Tella',
      'Tizi N\'Bechar',
    ],
    'Saïda': [
      'Saïda',
      'Aïn El Hadjar',
      'El Hassasna',
      'Maâta',
      'Moulay Larbi',
      'Ouled Brahim',
      'Sidi Ahmed',
      'Sidi Boubekeur',
      'Tircine',
      'Youb',
      'Aïn El Hadjar',
      'El Hassasna',
      'Maâta',
      'Moulay Larbi',
      'Ouled Brahim',
      'Sidi Ahmed',
      'Sidi Boubekeur',
      'Tircine',
      'Youb',
    ],
    'Skikda': [
      'Skikda',
      'Aïn Kechra',
      'Aïn Zouit',
      'Azzaba',
      'Ben Azzouz',
      'Collo',
      'El Hadaiek',
      'El Harrouch',
      'Es Sebt',
      'Filfila',
      'Hamadi Krouma',
      'Kanoua',
      'Kerkera',
      'Oued Zehour',
      'Ouled Attia',
      'Ouled Hebaba',
      'Ramdane Djamel',
      'Salah Bouchaour',
      'Sidi Mezghiche',
      'Tamalous',
      'Zerdazas',
      'Aïn Kechra',
      'Aïn Zouit',
      'Azzaba',
      'Ben Azzouz',
      'Collo',
      'El Hadaiek',
      'El Harrouch',
      'Es Sebt',
      'Filfila',
      'Hamadi Krouma',
      'Kanoua',
      'Kerkera',
      'Oued Zehour',
      'Ouled Attia',
      'Ouled Hebaba',
      'Ramdane Djamel',
      'Salah Bouchaour',
      'Sidi Mezghiche',
      'Tamalous',
      'Zerdazas',
    ],
    'Sidi Bel Abbès': [
      'Sidi Bel Abbès',
      'Aïn El Berd',
      'Ben Badis',
      'Marhoum',
      'Mérine',
      'Mostefa Ben Brahim',
      'Moulay Slissen',
      'Oued Taourira',
      'Ras El Ma',
      'Sfisef',
      'Sidi Ali Boussidi',
      'Sidi Ali Benyoub',
      'Sidi Brahim',
      'Sidi Chaïb',
      'Sidi Dahou Dehiles',
      'Sidi Hamadouche',
      'Sidi Khaled',
      'Sidi Lahcène',
      'Sidi Yacoub',
      'Tabia',
      'Télagh',
      'Ténira',
      'Tessala',
      'Tilmouni',
      'Zerouala',
      'Aïn El Berd',
      'Ben Badis',
      'Marhoum',
      'Mérine',
      'Mostefa Ben Brahim',
      'Moulay Slissen',
      'Oued Taourira',
      'Ras El Ma',
      'Sfisef',
      'Sidi Ali Boussidi',
      'Sidi Ali Benyoub',
      'Sidi Brahim',
      'Sidi Chaïb',
      'Sidi Dahou Dehiles',
      'Sidi Hamadouche',
      'Sidi Khaled',
      'Sidi Lahcène',
      'Sidi Yacoub',
      'Tabia',
      'Télagh',
      'Ténira',
      'Tessala',
      'Tilmouni',
      'Zerouala',
    ],
    'Annaba': [
      'Annaba',
      'Aïn Berda',
      'Berrahal',
      'Chetaïbi',
      'Cheurfa',
      'El Bouni',
      'El Hadjar',
      'Eulma',
      'Oued El Aneb',
      'Seraïdi',
      'Sidi Amar',
      'Treat',
      'Aïn Berda',
      'Berrahal',
      'Chetaïbi',
      'Cheurfa',
      'El Bouni',
      'El Hadjar',
      'Eulma',
      'Oued El Aneb',
      'Seraïdi',
      'Sidi Amar',
      'Treat',
    ],
    'Guelma': [
      'Guelma',
      'Aïn Ben Beida',
      'Aïn Larbi',
      'Aïn Makhlouf',
      'Aïn Reggada',
      'Belkheir',
      'Bordj Sabath',
      'Bou Hachana',
      'Bou Hamdane',
      'Bouati Mahmoud',
      'Bouchegouf',
      'Boumahra Ahmed',
      'Dahouara',
      'Djeballah Khemissi',
      'El Fedjoudj',
      'Guelaat Bou Sbaa',
      'Hammam Debagh',
      'Hammam N\'Bails',
      'Heliopolis',
      'Khezzara',
      'Medjez Amar',
      'Nechmaya',
      'Oued Cheham',
      'Oued Fragha',
      'Oued Zenati',
      'Ras El Agba',
      'Roknia',
      'Salaoua Announa',
      'Tamlouka',
      'Aïn Ben Beida',
      'Aïn Larbi',
      'Aïn Makhlouf',
      'Aïn Reggada',
      'Belkheir',
      'Bordj Sabath',
      'Bou Hachana',
      'Bou Hamdane',
      'Bouati Mahmoud',
      'Bouchegouf',
      'Boumahra Ahmed',
      'Dahouara',
      'Djeballah Khemissi',
      'El Fedjoudj',
      'Guelaat Bou Sbaa',
      'Hammam Debagh',
      'Hammam N\'Bails',
      'Heliopolis',
      'Khezzara',
      'Medjez Amar',
      'Nechmaya',
      'Oued Cheham',
      'Oued Fragha',
      'Oued Zenati',
      'Ras El Agba',
      'Roknia',
      'Salaoua Announa',
      'Tamlouka',
    ],
    'Constantine': [
      'Constantine',
      'Aïn Abid',
      'Aïn Smara',
      'Ben Badis',
      'Didouche Mourad',
      'El Khroub',
      'Hamma Bouziane',
      'Ibn Ziad',
      'Messaoud Boudjeriou',
      'Ouled Rahmoune',
      'Zighoud Youcef',
      'Aïn Abid',
      'Aïn Smara',
      'Ben Badis',
      'Didouche Mourad',
      'El Khroub',
      'Hamma Bouziane',
      'Ibn Ziad',
      'Messaoud Boudjeriou',
      'Ouled Rahmoune',
      'Zighoud Youcef',
    ],
    'Médéa': [
      'Médéa',
      'Aïn Boucif',
      'Aziz',
      'Baâta',
      'Benchicao',
      'Beni Slimane',
      'Berrouaghia',
      'Bir Ghbalou',
      'Boghar',
      'Bou Aiche',
      'Bouaichoune',
      'Bouskene',
      'Chahbounia',
      'Chelalet El Adhaoura',
      'Cheniguel',
      'Derrag',
      'Djouab',
      'Draa Essamar',
      'El Azizia',
      'El Omaria',
      'El Guelbelkebir',
      'Hannacha',
      'Kef Lakhdar',
      'Khams Djouamaa',
      'Ksar El Boukhari',
      'Medjebar',
      'Meftaha',
      'Mezerana',
      'Mihoub',
      'Ouamri',
      'Oued Harbil',
      'Ouled Antar',
      'Ouled Bouachra',
      'Ouled Deidech',
      'Ouled Hellal',
      'Oum El Djalil',
      'Saneg',
      'Sedraia',
      'Seghouane',
      'Si Mahdjoub',
      'Sidi Damed',
      'Sidi Errabia',
      'Sidi Naamane',
      'Souagui',
      'Tablat',
      'Tamesguida',
      'Tizi Mahdi',
      'Zoubiria',
      'Aïn Boucif',
      'Aziz',
      'Baâta',
      'Benchicao',
      'Beni Slimane',
      'Berrouaghia',
      'Bir Ghbalou',
      'Boghar',
      'Bou Aiche',
      'Bouaichoune',
      'Bouskene',
      'Chahbounia',
      'Chelalet El Adhaoura',
      'Cheniguel',
      'Derrag',
      'Djouab',
      'Draa Essamar',
      'El Azizia',
      'El Omaria',
      'El Guelbelkebir',
      'Hannacha',
      'Kef Lakhdar',
      'Khams Djouamaa',
      'Ksar El Boukhari',
      'Medjebar',
      'Meftaha',
      'Mezerana',
      'Mihoub',
      'Ouamri',
      'Oued Harbil',
      'Ouled Antar',
      'Ouled Bouachra',
      'Ouled Deidech',
      'Ouled Hellal',
      'Oum El Djalil',
      'Saneg',
      'Sedraia',
      'Seghouane',
      'Si Mahdjoub',
      'Sidi Damed',
      'Sidi Errabia',
      'Sidi Naamane',
      'Souagui',
      'Tablat',
      'Tamesguida',
      'Tizi Mahdi',
      'Zoubiria',
    ],
    'Mostaganem': [
      'Mostaganem',
      'Aïn Boudinar',
      'Aïn Nouissy',
      'Aïn Sidi Chérif',
      'Aïn Tedles',
      'Benabdelmalek Ramdane',
      'Bouguirat',
      'Fornaka',
      'Hadjadj',
      'Hassi Mameche',
      'Kheïr Eddine',
      'Mazagran',
      'Mesra',
      'Nekmaria',
      'Oued El Kheïr',
      'Ouled Boughalem',
      'Ouled Maallah',
      'Safsaf',
      'Sayada',
      'Sidi Ali',
      'Sidi Bellater',
      'Sidi Lakhdar',
      'Souaflia',
      'Stidia',
      'Sour',
      'Tazgait',
      'Touahria',
      'Aïn Boudinar',
      'Aïn Nouissy',
      'Aïn Sidi Chérif',
      'Aïn Tedles',
      'Benabdelmalek Ramdane',
      'Bouguirat',
      'Fornaka',
      'Hadjadj',
      'Hassi Mameche',
      'Kheïr Eddine',
      'Mazagran',
      'Mesra',
      'Nekmaria',
      'Oued El Kheïr',
      'Ouled Boughalem',
      'Ouled Maallah',
      'Safsaf',
      'Sayada',
      'Sidi Ali',
      'Sidi Bellater',
      'Sidi Lakhdar',
      'Souaflia',
      'Stidia',
      'Sour',
      'Tazgait',
      'Touahria',
    ],
    'M\'Sila': [
      'M\'Sila',
      'Aïn El Hadjel',
      'Aïn El Melh',
      'Aïn Rich',
      'Aïn Khadra',
      'Ben Srour',
      'Belaïba',
      'Berhoum',
      'Bir Foda',
      'Bou Saâda',
      'Chellal',
      'Dehahna',
      'Djebel Messaad',
      'El Hamel',
      'El Houamed',
      'Hammam Dalaa',
      'Khoubana',
      'Maadid',
      'Magra',
      'M\'Cif',
      'Medjedel',
      'Ouanougha',
      'Ouled Derradj',
      'Ouled Madhi',
      'Ouled Mansour',
      'Ouled Sidi Brahim',
      'Ouled Slimane',
      'Sidi Aïssa',
      'Sidi Hadjeres',
      'Sidi M\'Hamed',
      'Souamaa',
      'Tamsa',
      'Zarzour',
      'Aïn El Hadjel',
      'Aïn El Melh',
      'Aïn Rich',
      'Aïn Khadra',
      'Ben Srour',
      'Belaïba',
      'Berhoum',
      'Bir Foda',
      'Bou Saâda',
      'Chellal',
      'Dehahna',
      'Djebel Messaad',
      'El Hamel',
      'El Houamed',
      'Hammam Dalaa',
      'Khoubana',
      'Maadid',
      'Magra',
      'M\'Cif',
      'Medjedel',
      'Ouanougha',
      'Ouled Derradj',
      'Ouled Madhi',
      'Ouled Mansour',
      'Ouled Sidi Brahim',
      'Ouled Slimane',
      'Sidi Aïssa',
      'Sidi Hadjeres',
      'Sidi M\'Hamed',
      'Souamaa',
      'Tamsa',
      'Zarzour',
    ],
    'Mascara': [
      'Mascara',
      'Aïn Fares',
      'Aïn Fekan',
      'Aïn Ferah',
      'Aïn Frass',
      'Alaimia',
      'Aouf',
      'Beniane',
      'Bou Hanifia',
      'El Bordj',
      'El Gaada',
      'Ferraguig',
      'Froha',
      'Gharrous',
      'Guerdjoum',
      'Ghriss',
      'Guittena',
      'Hacine',
      'Khalouia',
      'Makdha',
      'Mamounia',
      'Maoussa',
      'Mohammadia',
      'Nesmoth',
      'Oggaz',
      'Oued El Abtal',
      'Oued Taria',
      'Ras El Aïn Amirouche',
      'Sedjerara',
      'Sehailia',
      'Sidi Abdeldjebar',
      'Sidi Abdelmoumen',
      'Sidi Boussaid',
      'Sidi Kada',
      'Sig',
      'Tighennif',
      'Tizi',
      'Zahana',
      'Aïn Fares',
      'Aïn Fekan',
      'Aïn Ferah',
      'Aïn Frass',
      'Alaimia',
      'Aouf',
      'Beniane',
      'Bou Hanifia',
      'El Bordj',
      'El Gaada',
      'Ferraguig',
      'Froha',
      'Gharrous',
      'Guerdjoum',
      'Ghriss',
      'Guittena',
      'Hacine',
      'Khalouia',
      'Makdha',
      'Mamounia',
      'Maoussa',
      'Mohammadia',
      'Nesmoth',
      'Oggaz',
      'Oued El Abtal',
      'Oued Taria',
      'Ras El Aïn Amirouche',
      'Sedjerara',
      'Sehailia',
      'Sidi Abdeldjebar',
      'Sidi Abdelmoumen',
      'Sidi Boussaid',
      'Sidi Kada',
      'Sig',
      'Tighennif',
      'Tizi',
      'Zahana',
    ],
    'Ouargla': [
      'Ouargla',
      'Aïn Beïda',
      'El Borma',
      'El Hadjira',
      'Hassi Messaoud',
      'Hassi R\'Mel',
      'M\'Ghaier',
      'N\'Goussa',
      'Rouissat',
      'Sidi Khouiled',
      'Taïbet',
      'Temacine',
      'Touggourt',
      'Zaouia El Abidia',
      'Aïn Beïda',
      'El Borma',
      'El Hadjira',
      'Hassi Messaoud',
      'Hassi R\'Mel',
      'M\'Ghaier',
      'N\'Goussa',
      'Rouissat',
      'Sidi Khouiled',
      'Taïbet',
      'Temacine',
      'Touggourt',
      'Zaouia El Abidia',
    ],
    'Oran': [
      'Oran',
      'Aïn El Turk',
      'Arzew',
      'Ben Freha',
      'Béthioua',
      'Bir El Djir',
      'Boufatis',
      'Bousfer',
      'El Ançor',
      'El Braya',
      'El Karma',
      'Es Senia',
      'Gdyel',
      'Hassi Ben Okba',
      'Hassi Bounif',
      'Hassi Mefsoukh',
      'Mers El Kébir',
      'Misserghin',
      'Oued Tlelat',
      'Sidi Ben Yebka',
      'Sidi Chami',
      'Tafraoui',
      'Aïn El Turk',
      'Arzew',
      'Ben Freha',
      'Béthioua',
      'Bir El Djir',
      'Boufatis',
      'Bousfer',
      'El Ançor',
      'El Braya',
      'El Karma',
      'Es Senia',
      'Gdyel',
      'Hassi Ben Okba',
      'Hassi Bounif',
      'Hassi Mefsoukh',
      'Mers El Kébir',
      'Misserghin',
      'Oued Tlelat',
      'Sidi Ben Yebka',
      'Sidi Chami',
      'Tafraoui',
    ],
    'El Bayadh': [
      'El Bayadh',
      'Boussemghoun',
      'Brezina',
      'Chellala',
      'El Abiodh Sidi Cheikh',
      'El Kheither',
      'Kef El Ahmar',
      'Rogassa',
      'Stitten',
      'Aïn El Orak',
      'Arbaouat',
      'Boualem',
      'Bougtob',
      'El Bnoud',
      'El Mehara',
      'Ghassoul',
      'Krakda',
      'Labiodh Sidi Cheikh',
      'Sidi Ameur',
      'Sidi Slimane',
      'Tousmouline',
      'Boussemghoun',
      'Brezina',
      'Chellala',
      'El Abiodh Sidi Cheikh',
      'El Kheither',
      'Kef El Ahmar',
      'Rogassa',
      'Stitten',
      'Aïn El Orak',
      'Arbaouat',
      'Boualem',
      'Bougtob',
      'El Bnoud',
      'El Mehara',
      'Ghassoul',
      'Krakda',
      'Labiodh Sidi Cheikh',
      'Sidi Ameur',
      'Sidi Slimane',
      'Tousmouline',
    ],
    'Illizi': [
      'Illizi',
      'Djanet',
      'In Amenas',
      'Bordj Omar Driss',
      'Debdeb',
      'In Guezzam',
      'Djanet',
      'In Amenas',
      'Bordj Omar Driss',
      'Debdeb',
      'In Guezzam',
    ],
    'Bordj Bou Arréridj': [
      'Bordj Bou Arréridj',
      'Aïn Taghrout',
      'Belimour',
      'Ben Daoud',
      'Bir Kasdali',
      'Bordj Ghédir',
      'Bordj Z\'Moura',
      'Colla',
      'Djaâfra',
      'El Ach',
      'El Achir',
      'El Anseur',
      'El Hamadia',
      'El Main',
      'El M\'Hir',
      'Ghilassa',
      'Haraza',
      'Hasnaoua',
      'Khelil',
      'Ksour',
      'Mansoura',
      'Medjana',
      'Ouled Brahem',
      'Ouled Dahmane',
      'Ouled Sidi Brahim',
      'Rabta',
      'Ras El Oued',
      'Sidi Embarek',
      'Taglait',
      'Tassamert',
      'Teniet En Nasr',
      'Tixter',
      'Aïn Taghrout',
      'Belimour',
      'Ben Daoud',
      'Bir Kasdali',
      'Bordj Ghédir',
      'Bordj Z\'Moura',
      'Colla',
      'Djaâfra',
      'El Ach',
      'El Achir',
      'El Anseur',
      'El Hamadia',
      'El Main',
      'El M\'Hir',
      'Ghilassa',
      'Haraza',
      'Hasnaoua',
      'Khelil',
      'Ksour',
      'Mansoura',
      'Medjana',
      'Ouled Brahem',
      'Ouled Dahmane',
      'Ouled Sidi Brahim',
      'Rabta',
      'Ras El Oued',
      'Sidi Embarek',
      'Taglait',
      'Tassamert',
      'Teniet En Nasr',
      'Tixter',
    ],
    'Boumerdès': [
      'Boumerdès',
      'Afir',
      'Baghlia',
      'Ben Choud',
      'Beni Amrane',
      'Bordj Menaïel',
      'Boudouaou',
      'Boudouaou El Bahri',
      'Bouzegza Keddara',
      'Chabet El Ameur',
      'Corso',
      'Dellys',
      'Djinet',
      'El Kharrouba',
      'Hammedi',
      'Isser',
      'Khemis El Khechna',
      'Larbatache',
      'Legata',
      'Naciria',
      'Ouled Aïssa',
      'Ouled Hedadj',
      'Ouled Moussa',
      'Si Mustapha',
      'Sidi Daoud',
      'Souk El Had',
      'Taourga',
      'Thenia',
      'Tidjelabine',
      'Timezrit',
      'Zemmouri',
      'Afir',
      'Baghlia',
      'Ben Choud',
      'Beni Amrane',
      'Bordj Menaïel',
      'Boudouaou',
      'Boudouaou El Bahri',
      'Bouzegza Keddara',
      'Chabet El Ameur',
      'Corso',
      'Dellys',
      'Djinet',
      'El Kharrouba',
      'Hammedi',
      'Isser',
      'Khemis El Khechna',
      'Larbatache',
      'Legata',
      'Naciria',
      'Ouled Aïssa',
      'Ouled Hedadj',
      'Ouled Moussa',
      'Si Mustapha',
      'Sidi Daoud',
      'Souk El Had',
      'Taourga',
      'Thenia',
      'Tidjelabine',
      'Timezrit',
      'Zemmouri',
    ],
    'El Tarf': [
      'El Tarf',
      'Aïn El Assel',
      'Aïn Kerma',
      'Asfour',
      'Béni M\'Hidi',
      'Berrihane',
      'Besbes',
      'Bouhadjar',
      'Bouteldja',
      'Chebaita Mokhtar',
      'Chefia',
      'Chihani',
      'Drean',
      'El Kala',
      'El Taref',
      'Hammam Beni Salah',
      'Lac des Oiseaux',
      'Oued Zitoun',
      'Raml Souk',
      'Souarekh',
      'Zerizer',
      'Zitouna',
      'Aïn El Assel',
      'Aïn Kerma',
      'Asfour',
      'Béni M\'Hidi',
      'Berrihane',
      'Besbes',
      'Bouhadjar',
      'Bouteldja',
      'Chebaita Mokhtar',
      'Chefia',
      'Chihani',
      'Drean',
      'El Kala',
      'El Taref',
      'Hammam Beni Salah',
      'Lac des Oiseaux',
      'Oued Zitoun',
      'Raml Souk',
      'Souarekh',
      'Zerizer',
      'Zitouna',
    ],
    'Tindouf': ['Tindouf', 'Oum El Assel', 'Oum El Assel'],
    'Tissemsilt': [
      'Tissemsilt',
      'Ammari',
      'Bordj El Emir Abdelkader',
      'Bordj Bounaama',
      'Boucaid',
      'Khemisti',
      'Lardjem',
      'Lazharia',
      'Maâcem',
      'Melaab',
      'Ouled Bessem',
      'Sidi Abed',
      'Sidi Boutouchent',
      'Sidi Lantri',
      'Tamellahet',
      'Théniet El Had',
      'Youssoufia',
      'Ammari',
      'Bordj El Emir Abdelkader',
      'Bordj Bounaama',
      'Boucaid',
      'Khemisti',
      'Lardjem',
      'Lazharia',
      'Maâcem',
      'Melaab',
      'Ouled Bessem',
      'Sidi Abed',
      'Sidi Boutouchent',
      'Sidi Lantri',
      'Tamellahet',
      'Théniet El Had',
      'Youssoufia',
    ],
    'El Oued': [
      'El Oued',
      'Bayadha',
      'Debila',
      'Djamaa',
      'Doucen',
      'El M\'Ghair',
      'Guemar',
      'Hassi Khalifa',
      'Magrane',
      'Mih Ouensa',
      'Nakhla',
      'Oued El Alenda',
      'Oum Touyour',
      'Ourmes',
      'Reguiba',
      'Robbah',
      'Still',
      'Taghzout',
      'Taleb Larbi',
      'Tendla',
      'Trifaoui',
      'Bayadha',
      'Debila',
      'Djamaa',
      'Doucen',
      'El M\'Ghair',
      'Guemar',
      'Hassi Khalifa',
      'Magrane',
      'Mih Ouensa',
      'Nakhla',
      'Oued El Alenda',
      'Oum Touyour',
      'Ourmes',
      'Reguiba',
      'Robbah',
      'Still',
      'Taghzout',
      'Taleb Larbi',
      'Tendla',
      'Trifaoui',
    ],
    'Khenchela': [
      'Khenchela',
      'Aïn Touila',
      'Babar',
      'Bouhmama',
      'Chelia',
      'El Hamma',
      'El Oueldja',
      'Ensigha',
      'Ferkane',
      'Kais',
      'Khirane',
      'M\'Sara',
      'M\'Toussa',
      'Ouled Rechache',
      'Remila',
      'Tamza',
      'Yabous',
      'Aïn Touila',
      'Babar',
      'Bouhmama',
      'Chelia',
      'El Hamma',
      'El Oueldja',
      'Ensigha',
      'Ferkane',
      'Kais',
      'Khirane',
      'M\'Sara',
      'M\'Toussa',
      'Ouled Rechache',
      'Remila',
      'Tamza',
      'Yabous',
    ],
    'Souk Ahras': [
      'Souk Ahras',
      'Aïn Zana',
      'Bir Bouhouche',
      'Drea',
      'Haddada',
      'Hanancha',
      'Khedara',
      'M\'Daourouche',
      'Mechroha',
      'Merahna',
      'Ouled Driss',
      'Oum El Adhaim',
      'Ragouba',
      'Safel El Ouiden',
      'Sedrata',
      'Taoura',
      'Terraguelt',
      'Tiffech',
      'Zaarouria',
      'Aïn Zana',
      'Bir Bouhouche',
      'Drea',
      'Haddada',
      'Hanancha',
      'Khedara',
      'M\'Daourouche',
      'Mechroha',
      'Merahna',
      'Ouled Driss',
      'Oum El Adhaim',
      'Ragouba',
      'Safel El Ouiden',
      'Sedrata',
      'Taoura',
      'Terraguelt',
      'Tiffech',
      'Zaarouria',
    ],
    'Tipaza': [
      'Tipaza',
      'Ahmer El Aïn',
      'Aïn Tagourait',
      'Attatba',
      'Bou Ismaïl',
      'Bouharoun',
      'Chaiba',
      'Cherchell',
      'Damous',
      'Douaouda',
      'Fouka',
      'Gouraya',
      'Hadjout',
      'Hadjeret Ennous',
      'Kolea',
      'Larhat',
      'Menaceur',
      'Merad',
      'Messelmoun',
      'Nador',
      'Sidi Amar',
      'Sidi Ghiles',
      'Sidi Rached',
      'Sidi Semiane',
      'Ahmer El Aïn',
      'Aïn Tagourait',
      'Attatba',
      'Bou Ismaïl',
      'Bouharoun',
      'Chaiba',
      'Cherchell',
      'Damous',
      'Douaouda',
      'Fouka',
      'Gouraya',
      'Hadjout',
      'Hadjeret Ennous',
      'Kolea',
      'Larhat',
      'Menaceur',
      'Merad',
      'Messelmoun',
      'Nador',
      'Sidi Amar',
      'Sidi Ghiles',
      'Sidi Rached',
      'Sidi Semiane',
    ],
    'Mila': [
      'Mila',
      'Aïn Beida Harriche',
      'Aïn Mellouk',
      'Aïn Tine',
      'Amira Arras',
      'Benyahia Abderrahmane',
      'Bouhatem',
      'Chelghoum Laïd',
      'Chigara',
      'Derradji Bousselah',
      'El Mechira',
      'El Taref',
      'Ferdjioua',
      'Grarem Gouga',
      'Hamala',
      'Mila',
      'Minar Zarza',
      'Oued Athmania',
      'Oued Endja',
      'Oued Seguen',
      'Ouled Khalouf',
      'Rouached',
      'Sidi Khelifa',
      'Sidi Merouane',
      'Tadjenanet',
      'Tassadane Haddada',
      'Teleghma',
      'Terrai Bainen',
      'Tessala Lamtai',
      'Tiberguent',
      'Yahia Beniguecha',
      'Zeghaia',
      'Aïn Beida Harriche',
      'Aïn Mellouk',
      'Aïn Tine',
      'Amira Arras',
      'Benyahia Abderrahmane',
      'Bouhatem',
      'Chelghoum Laïd',
      'Chigara',
      'Derradji Bousselah',
      'El Mechira',
      'El Taref',
      'Ferdjioua',
      'Grarem Gouga',
      'Hamala',
      'Mila',
      'Minar Zarza',
      'Oued Athmania',
      'Oued Endja',
      'Oued Seguen',
      'Ouled Khalouf',
      'Rouached',
      'Sidi Khelifa',
      'Sidi Merouane',
      'Tadjenanet',
      'Tassadane Haddada',
      'Teleghma',
      'Terrai Bainen',
      'Tessala Lamtai',
      'Tiberguent',
      'Yahia Beniguecha',
      'Zeghaia',
    ],
    'Aïn Defla': [
      'Aïn Defla',
      'Aïn Lechiakh',
      'Aïn Soltane',
      'Arib',
      'Bathia',
      'Belaas',
      'Ben Allal',
      'Bir Ouled Khelifa',
      'Bordj El Amir Khaled',
      'Boumedfaa',
      'Djelida',
      'Djemaa Ouled Cheikh',
      'El Abadia',
      'El Amra',
      'El Attaf',
      'Hammam Righa',
      'Hoceinia',
      'Khemis Miliana',
      'Mekhatria',
      'Miliana',
      'Oued Chorfa',
      'Oued Djemaa',
      'Rouina',
      'Sidi Lakhdar',
      'Tacheta Zougagha',
      'Tarik Ibn Ziad',
      'Tiberkanine',
      'Zeddine',
      'Aïn Lechiakh',
      'Aïn Soltane',
      'Arib',
      'Bathia',
      'Belaas',
      'Ben Allal',
      'Bir Ouled Khelifa',
      'Bordj El Amir Khaled',
      'Boumedfaa',
      'Djelida',
      'Djemaa Ouled Cheikh',
      'El Abadia',
      'El Amra',
      'El Attaf',
      'Hammam Righa',
      'Hoceinia',
      'Khemis Miliana',
      'Mekhatria',
      'Miliana',
      'Oued Chorfa',
      'Oued Djemaa',
      'Rouina',
      'Sidi Lakhdar',
      'Tacheta Zougagha',
      'Tarik Ibn Ziad',
      'Tiberkanine',
      'Zeddine',
    ],
    'Naâma': [
      'Naâma',
      'Aïn Sefra',
      'Asla',
      'Djeniene Bourezg',
      'El Biodh',
      'Kasdir',
      'Mecheria',
      'Moghrar',
      'Naâma',
      'Sfissifa',
      'Tiout',
      'Aïn Sefra',
      'Asla',
      'Djeniene Bourezg',
      'El Biodh',
      'Kasdir',
      'Mecheria',
      'Moghrar',
      'Naâma',
      'Sfissifa',
      'Tiout',
    ],
    'Aïn Témouchent': [
      'Aïn Témouchent',
      'Aghlal',
      'Aïn El Arbaa',
      'Aïn Kihal',
      'Aïn Tolba',
      'Beni Saf',
      'Bou Zedjar',
      'Chaabat El Ham',
      'Chentouf',
      'El Amria',
      'El Malah',
      'El Messaid',
      'Hammam Bou Hadjar',
      'Hassasna',
      'Oued Berkeche',
      'Oued Sebâa',
      'Ouled Boudjemaa',
      'Ouled Kihal',
      'Ouled Mimoun',
      'Sidi Ben Adda',
      'Sidi Boumediene',
      'Sidi Ouriache',
      'Sidi Safi',
      'Tamzoura',
      'Terga',
      'Aghlal',
      'Aïn El Arbaa',
      'Aïn Kihal',
      'Aïn Tolba',
      'Beni Saf',
      'Bou Zedjar',
      'Chaabat El Ham',
      'Chentouf',
      'El Amria',
      'El Malah',
      'El Messaid',
      'Hammam Bou Hadjar',
      'Hassasna',
      'Oued Berkeche',
      'Oued Sebâa',
      'Ouled Boudjemaa',
      'Ouled Kihal',
      'Ouled Mimoun',
      'Sidi Ben Adda',
      'Sidi Boumediene',
      'Sidi Ouriache',
      'Sidi Safi',
      'Tamzoura',
      'Terga',
    ],
    'Ghardaïa': [
      'Ghardaïa',
      'Berriane',
      'Bounoura',
      'Dhayet Bendhahoua',
      'El Atteuf',
      'El Guerrara',
      'El Meniaa',
      'Metlili',
      'Sebseb',
      'Zelfana',
      'Berriane',
      'Bounoura',
      'Dhayet Bendhahoua',
      'El Atteuf',
      'El Guerrara',
      'El Meniaa',
      'Metlili',
      'Sebseb',
      'Zelfana',
    ],
    'Relizane': [
      'Relizane',
      'Aïn Rahma',
      'Ammi Moussa',
      'Belaassel Bouzegza',
      'Beni Dergoun',
      'Beni Zentis',
      'Dar Ben Abdellah',
      'Djidiouia',
      'El Guettar',
      'El Hamadna',
      'El Matmar',
      'El Ouldja',
      'Had Echkalla',
      'Hamri',
      'Lahlef',
      'Mazouna',
      'Mediouna',
      'Mendes',
      'Merine',
      'M\'Yacoub',
      'Oued El Djemaa',
      'Oued Rhiou',
      'Ouled Aiche',
      'Ouled Sidi Mihoub',
      'Ramka',
      'Relizane',
      'Sidi Khettab',
      'Sidi Lazreg',
      'Sidi M\'Hamed Benaouda',
      'Sidi Saada',
      'Souk El Had',
      'Yellel',
      'Zemmoura',
      'Aïn Rahma',
      'Ammi Moussa',
      'Belaassel Bouzegza',
      'Beni Dergoun',
      'Beni Zentis',
      'Dar Ben Abdellah',
      'Djidiouia',
      'El Guettar',
      'El Hamadna',
      'El Matmar',
      'El Ouldja',
      'Had Echkalla',
      'Hamri',
      'Lahlef',
      'Mazouna',
      'Mediouna',
      'Mendes',
      'Merine',
      'M\'Yacoub',
      'Oued El Djemaa',
      'Oued Rhiou',
      'Ouled Aiche',
      'Ouled Sidi Mihoub',
      'Ramka',
      'Relizane',
      'Sidi Khettab',
      'Sidi Lazreg',
      'Sidi M\'Hamed Benaouda',
      'Sidi Saada',
      'Souk El Had',
      'Yellel',
      'Zemmoura',
    ],
  };

  static List<String> getAllWilayas() {
    return wilayas.keys.toList()..sort();
  }

  static List<String>? getBaladiyatForWilaya(String wilaya) {
    final baladiyat = wilayas[wilaya];
    if (baladiyat == null) return null;

    return baladiyat.toSet().toList();
  }

  static bool isValidAddress(String address) {
    final normalized = address.trim().toLowerCase();

    for (final wilaya in wilayas.keys) {
      if (normalized.contains(wilaya.toLowerCase())) {
        final baladiyat = wilayas[wilaya];
        if (baladiyat != null && baladiyat.isNotEmpty) {
          for (final baladiya in baladiyat) {
            if (normalized.contains(baladiya.toLowerCase())) {
              return true;
            }
          }
        }

        return true;
      }
    }

    return false;
  }

  static String? extractWilaya(String address) {
    final normalized = address.trim().toLowerCase();
    for (final wilaya in wilayas.keys) {
      if (normalized.contains(wilaya.toLowerCase())) {
        return wilaya;
      }
    }
    return null;
  }

  static String? extractBaladiya(String address, String wilaya) {
    final normalized = address.trim().toLowerCase();
    final baladiyat = wilayas[wilaya];
    if (baladiyat != null) {
      for (final baladiya in baladiyat) {
        if (normalized.contains(baladiya.toLowerCase())) {
          return baladiya;
        }
      }
    }
    return null;
  }
}
